# Generated by Django 3.2.7 on 2021-11-09 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_auto_20211109_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='property_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='property_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
