# Generated by Django 3.2.7 on 2021-11-09 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_auto_20211109_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='Subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
