# Generated by Django 3.2.7 on 2021-11-12 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_auto_20211111_1409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertyinquiry',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='propertyinquiry',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='question',
            name='last_name',
        ),
    ]
