# Generated by Django 3.2.7 on 2021-10-16 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offsure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OFFPlanAndInvestment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PlanName', models.CharField(max_length=200)),
                ('Overview', models.TextField()),
                ('Location', models.CharField(max_length=200)),
                ('Price', models.CharField(max_length=100)),
                ('Completion_date', models.DateField()),
                ('Dashboard_Image', models.ImageField(upload_to='OfPlanInvesments/')),
                ('Developer', models.CharField(max_length=200, null=True)),
                ('Development_type', models.TextField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='offplangallery',
            name='image',
        ),
        migrations.AddField(
            model_name='offplangallery',
            name='Image',
            field=models.ImageField(null=True, upload_to='OfPlanInvesments/Gallery'),
        ),
        migrations.CreateModel(
            name='PaymentPlans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Instalment_name', models.CharField(max_length=100, null=True)),
                ('Installment_date', models.CharField(max_length=100, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offsure.offplanandinvestment')),
            ],
        ),
        migrations.AlterField(
            model_name='offplangallery',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offsure.offplanandinvestment'),
        ),
        migrations.DeleteModel(
            name='OfPlaneInvesments',
        ),
    ]
