# Generated by Django 3.2.7 on 2021-10-29 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offsure', '0002_auto_20211016_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='offplanandinvestment',
            name='Area',
            field=models.CharField(default='123', max_length=100),
        ),
        migrations.AddField(
            model_name='offplanandinvestment',
            name='num_baths',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='offplanandinvestment',
            name='num_bedrooms',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='offplanandinvestment',
            name='num_garage',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='offplangallery',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
