# Generated by Django 3.2.7 on 2021-10-29 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offsure', '0004_auto_20211029_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offplanandinvestment',
            name='Area',
            field=models.CharField(default='1', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='offplanandinvestment',
            name='num_baths',
            field=models.CharField(default='1', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='offplanandinvestment',
            name='num_garage',
            field=models.CharField(default='1', max_length=100, null=True),
        ),
    ]
