# Generated by Django 3.2.7 on 2021-11-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offsure', '0005_auto_20211029_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='offplanandinvestment',
            name='uploaded_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
