# Generated by Django 3.2.7 on 2021-11-12 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offsure', '0006_offplanandinvestment_uploaded_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='offplanandinvestment',
            name='LocationFrame',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='InvestmentPlans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investmentPlan', models.CharField(blank=True, max_length=100, null=True)),
                ('investmentDetails', models.TextField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offsure.offplanandinvestment')),
            ],
        ),
        migrations.CreateModel(
            name='Amenitie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offsure.offplanandinvestment')),
            ],
        ),
    ]
