# Generated by Django 3.2.7 on 2021-11-13 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offsure', '0008_auto_20211113_0903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offplanandinvestment',
            old_name='num_garage',
            new_name='num_Garage',
        ),
    ]
